// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrccbfvjnjcqjjjxkdkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyY2NiZnZqbmpjcWpqanhrZGttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDQyMDUsImV4cCI6MjA2MjgyMDIwNX0.5Z-ydlxfZ8wh2whhMryAq1jKcMoEpjqa8nq-EQ9Ws-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);